### ISSUE TITLE
Difference between declaration and real state

### ISSUE THREAD

**Issue by proft** [yogiben/meteor-autoform-map#44]
Hello!

I have that schema

```
@Places = new Mongo.Collection('Places')
PlacesSchema = new SimpleSchema
    title:
        type: String
        label: "Title"
        max: 250
        index: 1
    location:
        type: [Number] # lng, lat
        decimal: true
        label: 'Location'
        autoform:
            type: 'map'
            afFieldInput:
                searchBox: true
                height: '400px'
                zoom: 3
```

and on server startup 

```
Meteor.startup ->
    Places._ensureIndex({'location': '2dsphere'});
```

After that my field looks like

```
location: Object
 type: "Point"
▼coordinates: Array[2]
 0: 145.29833681
 1: -40.75822243
```

Notice, ``Object``, not ``Array``. 

As result it doesnt render map in form, only gray rectangle...

I try method ``rendered`` in ``afFieldInput``

```
                rendered: (map) ->
                    console.log this
                    console.log map
```

and it shows my 

```
Object {name: "location"}
undefined
```

I cant get the map object (.

How I can set coordinates or see map?
